### ISSUE TITLE
[Bug]  STRIPE: error with successful payment in STRIPE

### ISSUE THREAD

**Issue by elixon01** [FOSSBilling/FOSSBilling#1135]
### Describe the bug

Good afternoon, I have an error with the STRIPE payment platform when the customer makes the payment and the payment is successful, it DOES NOT redirect it to the website as successful, what it does is throw an error as shown in the image, nor does it activate the hosting. But if you register the payment in the database, what will this be due to??

![1a](https://user-images.githubusercontent.com/97003979/233691838-7a6a9f4d-2218-4603-a787-4e30c0e6c19a.jpg)
![2a](https://user-images.githubusercontent.com/97003979/233691860-568e3468-d191-41fc-ad98-be7116e5bc88.jpg)

### How to reproduce

Good afternoon, I have an error with the STRIPE payment platform when the customer makes the payment and the payment is successful, it DOES NOT redirect it to the website as successful, what it does is throw an error as shown in the image, nor does it activate the hosting. But if you register the payment in the database, what will this be due to??

### Expected behavior

Good afternoon, I have an error with the STRIPE payment platform when the customer makes the payment and the payment is successful, it DOES NOT redirect it to the website as successful, what it does is throw an error as shown in the image, nor does it activate the hosting. But if you register the payment in the database, what will this be due to??

### FOSSBilling version

4.2.0

### Module version

4.2

### Device

Desktop, Smartphone

### Information

Good afternoon, I have an error with the STRIPE payment platform when the customer makes the payment and the payment is successful, it DOES NOT redirect it to the website as successful, what it does is throw an error as shown in the image, nor does it activate the hosting. But if you register the payment in the database, what will this be due to??

### Additional context

Good afternoon, I have an error with the STRIPE payment platform when the customer makes the payment and the payment is successful, it DOES NOT redirect it to the website as successful, what it does is throw an error as shown in the image, nor does it activate the hosting. But if you register the payment in the database, what will this be due to??

**Comment by BelleNottelling** [comment]
I personally tested the stripe payment gateway before we made the 0.4.0 release, and I tested it in our dev branch less than 12 hours ago. It works perfectly fine for me.

I'll need you to edit your `config.php` file and set `debug` to `true`. Then, make a test transaction and share what's displayed on the screen & what appears in the error log under `/data/log`. That should tell us what file & where the error is coming from.

Once you get that info, you can set the `debug` option back to `false`

**Comment by elixon01** [comment]
Done, I already did what you told me and it gives me this error in the
payment? The first image is what gives me I give it f5 update and it
gives me those errors in the image



in the error log it did not give me

**Comment by elixon01** [comment]
Done, I already did what you told me and it gives me this error in the
payment? The first image is what gives me I give it f5 update and it
gives me those errors in the image



![3a](https://user-images.githubusercontent.com/97003979/233713536-7dff0a9d-3336-41c4-923d-52cb53750134.jpg)
![4a](https://user-images.githubusercontent.com/97003979/233713653-8f29b0dc-9866-4661-a689-2b02eb34f5c9.jpg)
![5a](https://user-images.githubusercontent.com/97003979/233713716-511130c8-6cf6-4451-a532-ffcf0b20e11a.jpg)
![6a](https://user-images.githubusercontent.com/97003979/233713765-ed35c2b5-4d29-4f05-8ada-abf146462584.jpg)
![7a](https://user-images.githubusercontent.com/97003979/233713821-2b58ee94-5f16-4fb6-a0e9-9db70a316a25.jpg)

**Comment by jaapmarcus** [comment]
https://github.com/FOSSBilling/FOSSBilling/blob/57444aa0c701f523213c876e2434849a9c7b75dd/src/library/Payment/Adapter/Stripe.php#L140

This is the line question. But it is also missing the api token

**Comment by BelleNottelling** [comment]
> Get request will not work you have to "fake" a post request to test it..

Yeah, it won't work for the transaction, but in this case the screenshots still show where the error is being thrown, so this is good enough

**Comment by BelleNottelling** [comment]
PR is up to fix this: https://github.com/FOSSBilling/FOSSBilling/pull/1139
