### ISSUE TITLE
[Bug] Cannot create auto create hosting package and user

### ISSUE THREAD

**Issue by Daandeve** [FOSSBilling/FOSSBilling#2306]
### Describe the bug

When I try to activate a webhosting order on a direct admin server the server returns 403 unauthorised, there seems to be a problem with the reseller option. When I remove lines 324 till 329 of the `library/Server/Manager/Directadmin.php` file everything seems to work fine.

### How to reproduce

1. Add a direct admin server to the system
2. Create a new hosting order
3. Activate the order

### Expected behavior

Activate the order on all types of direct admin installs

### FOSSBilling version

0.6.20

**Comment by j-a-pope** [comment]
I know that Adam is doing some work to update the DA module which will be done sometime in the near future. 

@admdly Will this be resolved by what you are doing?

**Comment by admdly** [comment]
@j-a-pope I don't believe anything relevant to this would be changed, but provided it can be replicated, I will also include a fix for this in my upcoming DA PR - it should be a fairly simple matter to resolve.

**Comment by Daandeve** [comment]
This issue not not yet solved, it still happens when I do not comment out lines 410 to 414
