### ISSUE TITLE
[Bug] Login to cPanel button is not working

### ISSUE THREAD

**Issue by afonsosantos** [FOSSBilling/FOSSBilling#2671]
### Describe the bug

When the client tries to login to the created cPanel account, the button on the service details page (Jump to cPanel) does not redirect the user there, instead it goes back to the home page.

### How to reproduce

1. Create a web hosting product
2. Associate a WHM server (version 126.0.14) and an existing package
3. Register as a customer and purchase that hosting package
4. Confirm the payment on the admin area and wait for the account to be created
5. On the client side, go to the order details and click on "Jump to cPanel"

### Expected behavior

The Jump to cPanel button should redirect the user to the cPanel account under my WHM server

### FOSSBilling version

0.6.22

### FOSSBilling instance ID

7f63c7db-6959-4c4c-8fd7-45d0126bdcb0

### Device

Desktop

### Information

- WHM version: 126.0.14

**Comment by BelleNottelling** [comment]
I believe this is likely already fixed in the current preview builds as we've implemented 1-click logins for WHM

**Comment by markmemayank** [comment]
Hey @BelleNottelling ,

I am also facing this issue. It's not sorted yet.

**Comment by markmemayank** [comment]
Hey @j-a-pope I am using latest release.

![Image](https://github.com/user-attachments/assets/a7ee1c4a-e229-4d3c-9996-c7b4478fc062)

**Comment by j-a-pope** [comment]
> Hey [@j-a-pope](https://github.com/j-a-pope) I am using latest release.

Yep, so I'm assuming that is 0.6.22

We are pretty certain that this has been fixed since then, so if you used the latest preview build then the error won't be there. Those changes will be in the next release which will be out sometime in May, if you prefer to wait for that.

**Comment by markmemayank** [comment]
Hey @j-a-pope Any update when this will be released? This error is still there.

**Comment by j-a-pope** [comment]
Have just tested and can confirm that this is resolved in the latest preview builds and will be included in the upcoming release, so I am closing this issue.
